### ISSUE TITLE
Create a page of External judge for manual marking Question 1

### ISSUE THREAD

**Issue by Gdsc-Cummins** [Google-Developer-Student-Club-CCOEW/Android-2023-GDSC-CUMMINS-X-GDSC-MMCOE#1]
**Hello contributors!** 

⇨ You have to create a page that will contain Question 1. The page will contain the following question and an editText where the the user will give marks out of 10.  Along with this add a button as "Next" which will navigate to the next question. You have to contribute for [XML](https://github.com/Google-Developer-Student-Club-CCOEW/Android-2023/blob/main/SIH%20Evaluation/app/src/main/res/layout/ext_auto_que1.xml) and [JAVA file](https://github.com/Google-Developer-Student-Club-CCOEW/Android-2023/blob/main/SIH%20Evaluation/app/src/main/java/com/example/sihevaluation/Ex_manual_que1.java). 

Que 1. Does the project solve a unique problem? Rate this on a scale of 1 to 10.

**Comment by Sonia312** [comment]
Please assign this issue to me
Sonia Dessai
TY Comp A
UCE2021414
sonia.dessai@cumminscollege.in

**Comment by Gdsc-Cummins** [comment]
Thank you for contributing Sonia
