### ISSUE TITLE
Mini-Projects : Simple-Calculator

### ISSUE THREAD

**Issue by gdsc-mmcoe** [Google-Developer-Student-Club-CCOEW/Android-2023-GDSC-CUMMINS-X-GDSC-MMCOE#50]
This project aims to create a user-friendly Simple Calculator app that provides essential arithmetic operations such as addition, subtraction, multiplication, and division. The app is designed to be intuitive and easy to use, making it a perfect choice for individuals who need a basic calculator tool on their Android devices. This project serves as an excellent introduction to Android app development using Java.

### Contribute to the following folder
- [Simple Calculator](https://github.com/Google-Developer-Student-Club-CCOEW/Android-2023-GDSC-CUMMINS-X-GDSC-MMCOE/tree/main/Mini-Projects/Simple-Calculator)

**Comment by 51tejalhajari** [comment]
can you please assign this issue to me 
tejal hajari
cummins college of engineering pune 
UEC2022151

**Comment by gdsc-mmcoe** [comment]
@51tejalhajari  u are assigned to this issue, please make pull request ASAP.

**Comment by PrathamAsaigoli** [comment]
can even i be assigned for this issue
Pratham Asaigoli
AJ Institute of Engineering and technology
